### PR TITLE
fix: keep index when sorting

### PR DESCRIPTION
**Pull request by kusiboss**

### CODE REVIEW

**Comment by tuxes3** [comment]
@kusiboss to not include a new BC, think of creating a new method `getAllIdentifier` or rewrite the `removeColumn` to loop though all columns and delete the one with the given identifier.

**Review by kusiboss — COMMENTED** [review]
Should have done two commits here: one for exportmanager and one for the test. Is there a way to split those?

**Review by tuxes3 — APPROVED** [review]

**Comment by tuxes3** [comment]
@rugbymauri do you see a case where this change is not wanted?

**Comment by tuxes3** [comment]
@kusiboss 

> Should have done two commits here: one for exportmanager and one for the test. Is there a way to split those?

with `git reset --soft HEAD~2` kannst du die 2 commits wider auflösen. Danach commitest du in der Reihenfolge wie du willst und danach kannst du ein force push machen um das ganze zu überschreiben. 

Anschliessend kannst du den branch mergen!

**Pull request merged**
